{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aperlambda",
    "module": "lambdajcommon",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "lb5mxaajbbb43on3u7toftcdtm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.1-jre"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "17.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lambdajcommon-1.8.1.jar",
          "url": "lambdajcommon-1.8.1.jar",
          "size": 45016,
          "sha512": "19bff5101ad78fe13a20f9648ff6f25ee777e5b92bba6e2c3eda2d2e45fd1aa55c0470bd9d594267dc1f29a0a47ef7a85c18cbe3cfa71feb2b10f847f425cf44",
          "sha256": "ac3b1201a8bab3b404bf06541ea21604de00ed3d22c062a9929d3dd4b7093d8a",
          "sha1": "54288ecdfdfe5a385fc9c9b0b9ea46866983def5",
          "md5": "5a5089b5bed033dc067e86bc5b0508b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.1-jre"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "17.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lambdajcommon-1.8.1.jar",
          "url": "lambdajcommon-1.8.1.jar",
          "size": 45016,
          "sha512": "19bff5101ad78fe13a20f9648ff6f25ee777e5b92bba6e2c3eda2d2e45fd1aa55c0470bd9d594267dc1f29a0a47ef7a85c18cbe3cfa71feb2b10f847f425cf44",
          "sha256": "ac3b1201a8bab3b404bf06541ea21604de00ed3d22c062a9929d3dd4b7093d8a",
          "sha1": "54288ecdfdfe5a385fc9c9b0b9ea46866983def5",
          "md5": "5a5089b5bed033dc067e86bc5b0508b3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lambdajcommon-1.8.1-javadoc.jar",
          "url": "lambdajcommon-1.8.1-javadoc.jar",
          "size": 543783,
          "sha512": "4eb7e2e14d570fb19b9c10402e7b31521f5c7f8f947ae959cd1f7f4d4a95bbe83bcd4fd45c117cec9fcd97a20ca3b71711ae424c48a4eebb6d31c6c18b80cb1",
          "sha256": "ba4fea8f4b9c5632589167f18726131ea1f46a3d9d6a40579f7a0e7cc2158050",
          "sha1": "8eadc0d87bd09d24ac8e4a8a3e0d156980183e74",
          "md5": "861b238706b69b626b155ba33ec7e066"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lambdajcommon-1.8.1-sources.jar",
          "url": "lambdajcommon-1.8.1-sources.jar",
          "size": 31759,
          "sha512": "17ecd931596c1a2c161a3dfe4cecd39e6aac2c9886631032748fe3b8ce97074248dccd3921f9a33779b5de6669ef16a0e972f52deb21aedc9407286d467b33a1",
          "sha256": "f01c9c2f411afb0fa7595b4a6ae779f6c331856a4eeb2dbf003b5d8864ce2708",
          "sha1": "fb1f8958a84edce3bc4c6e6dd0d1ec94ad537377",
          "md5": "27b13e968d0e3d5359d654cc6a823447"
        }
      ]
    }
  ]
}
